# Generated by Django 4.1.5 on 2023-11-21 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empleado', models.CharField(max_length=50)),
                ('apellido_empleado', models.CharField(max_length=50)),
                ('direccion_empleado', models.CharField(max_length=60)),
                ('telefono_empleado', models.CharField(max_length=12)),
                ('correo_empleado', models.CharField(max_length=70)),
                ('fecha_ingreso', models.DateField()),
                ('sueldo_base', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Facturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_facturacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rubro_proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rubro', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(max_length=50)),
                ('precio_servicio', models.IntegerField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva_hora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('apellido_cliente', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('Facturacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Serviexpress.facturacion')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Serviexpress.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proveedor', models.CharField(max_length=50)),
                ('direccion_proveedor', models.CharField(max_length=70)),
                ('telefono_proveedor', models.CharField(max_length=12)),
                ('correo_proveedor', models.CharField(max_length=70)),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Serviexpress.rubro_proveedor')),
            ],
        ),
    ]
